### ISSUE TITLE
How do you rebuild this jar file?

### ISSUE THREAD

**Issue by ShenkieRuben** [raadjoe/kr_forgetting#2]
The pom.xml that is provided does not work when I use mvn package. Which steps should I take to rebuild the jar file, because I have added some code.

**Comment by raadjoe** [comment]
In the Eclipse IDE, you can just: 
- right-click on the project,
- Click "Export..."
- Choose "Runnable JAR file"

**Comment by ShenkieRuben** [comment]
Thanks it works now!
